version: '3.8'

services:
  db:
    container_name: quote-db
    networks:
      - shared-network
    image: postgres:13.2-alpine
    ports:
      - 5432:5432 
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
    volumes:
        - db_postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: quote-pgadmin
    networks:
      - shared-network
    image: dpage/pgadmin4:4.23
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    restart: always
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - db

  quote-api:
    container_name: quote-api
    networks:
      - shared-network
    image: quote-api-amd64:1.0
    build:
      context: .
      dockerfile: dockerfile.quote-api
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
    db_postgres:
    pgadmin:

networks:
  shared-network:
    driver: bridge